server:
  port: 28122
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 102400
  # 请求前缀
  servlet:
    context-path: /ynkf-websocket
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  application:
    name: ynkf-websocket
  kafka:
    bootstrap-servers:
      hadoop23:9092 
      hadoop24:9092
      hadoop25:9092
    consumer:
      group-id: springboot-websocket

#mybatis:
#  mapper-locations: /mapper/*.xml

logging:
  level:
    com.hzsun.zbp.ownexactlydata.dao: debug
#  file: logs/data-assests.log


